// <auto-generated />
using System;
using BookStore_Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore_Infrastructure.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookStore_ApplicationCore.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3123),
                            Name = "Action",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3125),
                            Name = "Adventure",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3126),
                            Name = "Comedy",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3127),
                            Name = "Fantasy",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3128),
                            Name = "Horror",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3129),
                            Name = "Mystery",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3130),
                            Name = "Romance",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BookStore_ApplicationCore.Entities.Concrete.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1928, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(2594),
                            FirstName = "Stanley",
                            LastName = "Kubrick",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1933, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(2614),
                            FirstName = "Roman",
                            LastName = "Polanski",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(2616),
                            FirstName = "Quentine Jerome",
                            LastName = "Tarantino",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1897, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(2617),
                            FirstName = "Frank",
                            LastName = "Capra",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1962, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(2618),
                            FirstName = "David Leo",
                            LastName = "Fincher",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BookStore_ApplicationCore.Entities.Concrete.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3021),
                            Description = "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.",
                            DirectorId = 1,
                            Image = "1269f10b-aa48-4e93-b666-76ca1d34fa06_Full Metal Jacket.jpg",
                            Name = "Full Metal Jacket",
                            Status = 1,
                            Year = 1987
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3024),
                            Description = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future",
                            DirectorId = 1,
                            Image = "6c472c63-5322-4081-b558-1ea594fca0d0_The Shining.jpg",
                            Name = "The Shining",
                            Status = 1,
                            Year = 1980
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3026),
                            Description = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II",
                            DirectorId = 2,
                            Image = "d116b47d-4705-4f88-bb48-409714ec7c58_The Pianist.jpg",
                            Name = "The Pianist",
                            Status = 1,
                            Year = 2002
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3027),
                            Description = "In 1894, French Captain Alfred Dreyfus is wrongfully convicted of treason and sentenced to life imprisonment at Devil's island",
                            DirectorId = 2,
                            Image = "d61f21ba-57eb-49d8-bb88-3c3500af5f75_An Officer and Spy.jpg",
                            Name = "An Offices and Spy",
                            Status = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3028),
                            Description = "A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles",
                            DirectorId = 3,
                            Image = "a501a3f6-530d-4cb1-b7f2-26bd1eb8ac6b_Once Upon a Time in Hollywood.jpg",
                            Name = "Once Upon a Time in Hollywood",
                            Status = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3029),
                            Description = "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.",
                            DirectorId = 3,
                            Image = "1786becb-0d95-4eab-b103-14e1164e4dfa_Kill Bill Volume 1.jpg",
                            Name = "Kill Bill Volume 1",
                            Status = 1,
                            Year = 2003
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3030),
                            Description = "A Broadway matinee idol famous for his black-face portrayals anonymously joins an amateur acting troupe and falls in love with the leading lady",
                            DirectorId = 4,
                            Image = "13d01d4f-6249-4861-bed5-51aa43b6302a_The Matinee Idol.jpg",
                            Name = "The Matinee Idol",
                            Status = 1,
                            Year = 1928
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3031),
                            Description = "Naive newspaper cub Clem lands a scoop when he's sent out to cover a murder. In his enthusiasm he writes that the main suspect is Jane. When she confronts Clem she convinces him to help her prove her innocence",
                            DirectorId = 4,
                            Image = "2d97dc9f-3047-4460-9895-d122e671690c_Power_of_the_pressmp.jpg",
                            Name = "The Power Of The Press",
                            Status = 1,
                            Year = 1928
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3033),
                            Description = "Tells the story of Benjamin Button, a man who starts aging backwards with consequences",
                            DirectorId = 5,
                            Image = "73297031-ae64-4231-9bac-51e834a0fe04_The Curios Case of Benjamin Button.jpg",
                            Name = "The Curios Case of Benjamin Button",
                            Status = 1,
                            Year = 2008
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 9, 3, 11, 35, 15, 654, DateTimeKind.Local).AddTicks(3034),
                            Description = "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea and by the co-founder who was later squeezed out of the business",
                            DirectorId = 5,
                            Image = "a919191b-0917-4b7c-9c69-a9f8cb0ae5ff_The_Social_Network_film_poster.png",
                            Name = "The Social Network",
                            Status = 1,
                            Year = 2010
                        });
                });

            modelBuilder.Entity("BookStore_ApplicationCore.Entities.Concrete.MovieCategory", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("BookStore_ApplicationCore.Entities.Concrete.Movie", b =>
                {
                    b.HasOne("BookStore_ApplicationCore.Entities.Concrete.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("BookStore_ApplicationCore.Entities.Concrete.MovieCategory", b =>
                {
                    b.HasOne("BookStore_ApplicationCore.Entities.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore_ApplicationCore.Entities.Concrete.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BookStore_ApplicationCore.Entities.Concrete.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
